create unique index "proteinDataUniqueIndex" on "proteinData"("cancerId", "geneId", "participantId");
create unique index "phosphoproteinDataUniqueIndex" on "phosphoproteinData"("cancerId", "geneId", "participantId", "accession", "phosphorylationSite", "phosphopeptide");
create unique index "phosphoproteinRatioDataUniqueIndex" on "phosphoproteinRatioData"("cancerId", "geneId", "participantId", "accession", "phosphorylationSite", "phosphopeptide");
create unique index "rnaDataUniqueIndex" on "rnaData"("cancerId", "geneId", "participantId");
create unique index "tcgaRnaDataUniqueIndex" on "tcgaRnaData"("cancerId", "geneId", "participantId");
create unique index "proteinDataSummaryUniqueIndex" on "proteinDataSummary"("cancerId", "geneId");
create unique index "phosphoproteinDataSummaryUniqueIndex" on "phosphoproteinDataSummary"("cancerId", "geneId", "accession", "phosphorylationSite", "phosphopeptide");
create unique index "phosphoproteinRatioDataSummaryUniqueIndex" on "phosphoproteinRatioDataSummary"("cancerId", "geneId", "accession", "phosphorylationSite", "phosphopeptide");
create unique index "rnaDataSummaryUniqueIndex" on "rnaDataSummary"("cancerId", "geneId");
create unique index "tcgaRnaDataSummaryUniqueIndex" on "tcgaRnaDataSummary"("cancerId", "geneId");
